name: gcs-cam
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - numpy=1.23.3
  - numpy-base=1.23.3
  - asttokens=2.0.5
  - backcall=0.2.0
  - blas=1.0=mkl
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates
  - certifi=2022.9.24
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - colorcet=3.0.0
  - cryptography=37.0.1
  - cudatoolkit=11.6.0
  - cycler=0.11.0
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.2.10
  - ffmpeg=4.3
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.10.4
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.13
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=3.7.0
  - hdf5=1.10.6
  - icu=58.2
  - idna=3.4
  - intel-openmp=2021.4.0
  - ipykernel=6.15.2
  - ipython=8.4.0
  - jedi=0.18.1
  - joblib=1.2.0
  - jpeg=9e
  - jupyter_client=7.3.5
  - jupyter_core=4.11.1
  - keyutils=1.6.1
  - kiwisolver=1.4.2
  - krb5=1.19.3
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libblas=3.9.0=12_linux64_mkl
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0=12_linux64_mkl
  - libclang=10.0.1
  - libdeflate=1.8
  - libedit=3.1.20191231
  - libevent=2.1.12
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libiconv=1.17
  - liblapack=3.9.0=12_linux64_mkl
  - libllvm10=10.0.1
  - libpng=1.6.37
  - libpq=12.9
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtiff=4.4.0
  - libuuid=1.0.3
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.3
  - libxml2=2.9.14
  - libxslt=1.1.35
  - lz4-c=1.9.3
  - matplotlib=3.5.2
  - matplotlib-base=3.5.2
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - nettle=3.6
  - nspr=4.33
  - nss=3.74
  - numpy=1.23.3
  - numpy-base=1.23.3
  - openh264=2.1.1
  - openssl=1.1.1q
  - packaging=21.3
  - param=1.12.0
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.2.2
  - ply=3.11
  - prompt-toolkit=3.0.20
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pyct=0.4.8
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pysocks=1.7.1
  - python=3.10.6
  - python-dateutil=2.8.2
  - python_abi
  - pytorch=1.12.1=py3.10_cuda11.6_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - pyzmq=23.2.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.1.2
  - requests=2.28.1
  - scikit-learn=1.1.1
  - scipy=1.8.1
  - setuptools=63.4.1
  - sip=6.6.2
  - six=1.16.0
  - sqlite=3.39.3
  - stack_data=0.2.0
  - threadpoolctl=3.1.0
  - timm=0.4.12
  - tk=8.6.12
  - toml=0.10.2
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - tornado=6.2
  - tqdm=4.64.1
  - traitlets=5.1.1
  - typing_extensions=4.4.0
  - tzdata=2022e
  - urllib3=1.26.12
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - grad-cam==1.4.6
    - opencv-python==4.6.0.66
    - pyqt5-sip==12.11.0
    - pyyaml==6.0
    - ttach==0.0.3
